export function generateId(): string
export function generatePrefixedId(prefix: string): string
export function generateUserId(): string
export function generateTenantId(): string
export function generateSessionId(): string
export function generateOnboardingId(): string
export function generatePermissionId(): string
export function generateRoleId(): string
export function generateRolePermissionsId(): string
export function generateVerificationId(): string
export function generateAssetId(): string
export function generateAssetUploadId(): string
export function generateFileId(): string
export function generateReceiptId(): string
export function generateInvoiceReceiptId(): string
export function generateCreditNoteId(): string
export function generateDebitNoteId(): string
export function generateProformaInvoiceId(): string
export function generateDeliveryNoteId(): string
export function generateOrderId(): string
export function generateQuoteId(): string
export function generateCustomerId(): string
export function generatePaymentId(): string
export function generateTransactionId(): string
export function generateSupplierId(): string
export function generateInvoiceId(): string
export function generateInvoiceItemId(): string
export function generateInvoiceCorrectionId(): string
export function generateCounterpartyId(): string
export function generateDocumentDataId(): string
export function generateBotFlowId(): string
export function generateCorrelationId(): string
export function generateEventId(): string
export function generateJobId(): string
export function generateTaskId(): string
export function generateQueueId(): string
export function generateMessageId(): string
export function generateEmailId(): string
export function generateIncomingEmailId(): string
export function generateImId(): string
export function generateNotificationId(): string
export function generateAuditId(): string
export function generateLogId(): string
export function generateMetricId(): string
export function generateKeyId(): string
export function generatePolicyId(): string
export function generateProfileId(): string
export function generateDeviceId(): string
export function generateAlertId(): string
export function generateResourceId(): string
export function generateTagId(): string
export function generateConfigId(): string
